version: '3.8'

services:
  flask:
    build: ./src/
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./src:/usr/src/
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hackathon


volumes:
  postgres_data:

